from __future__ import annotations
import os
import sys
from pathlib import Path

HOOK_CONTENT = """#!/bin/sh
# CONTINUITY LEGACY PRE-COMMIT HOOK
# Automatically generated by the Continental Legacy framework.

echo "[*] CONTINUITY LEGACY: Validating project state before commit..."

# Execute the continuity cycle in strict mode
# We use 'python' assuming it's in the PATH, fallback to sys.executable logic if needed
python tools/continuity_legacy/run_continuity_cycle.py --repo-root . --strict

# $? captures the exit code of the last command
RESULT=$?

if [ $RESULT -ne 0 ]; then
  echo "[!] CONTINUITY ERROR: Project state is inconsistent. Commit blocked."
  echo "[!] Please run 'python tools/continuity_legacy/run_continuity_cycle.py' and fix issues."
  exit 1
fi

echo "[✔] CONTINUITY OK: Project state is valid. Proceeding with commit."
exit 0
"""

def install_pre_commit_hook(repo_root: str | Path) -> bool:
    repo_root = Path(repo_root).resolve()
    git_dir = repo_root / ".git"
    
    if not git_dir.exists():
        # Not a git repo, skip hooks
        return False
        
    hooks_dir = git_dir / "hooks"
    hooks_dir.mkdir(parents=True, exist_ok=True)
    
    hook_file = hooks_dir / "pre-commit"
    
    try:
        hook_file.write_text(HOOK_CONTENT, encoding="utf-8")
        
        # On Unix-like systems (including Git Bash on Windows), we need to make it executable
        if os.name != 'nt':
            os.chmod(hook_file, 0o755)
            
        return True
    except Exception as e:
        print(f"Error installing git hook: {e}")
        return False

if __name__ == "__main__":
    # Test installation in current dir
    if install_pre_commit_hook("."):
        print("Pre-commit hook installed successfully.")
    else:
        print("Failed to install pre-commit hook (Are you in a git repo?).")
