name: Publish to PyPI 🚀

on:
  release:
    types: [published]

jobs:
  build-n-publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code 📂
      uses: actions/checkout@v3

    - name: Set up Python 🐍
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    - name: Install dependencies 📦
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: Build Pro Edition 🔱
      run: |
        cd "CONTINUITY LEGACY Pro"
        python -m build

    - name: Build Lite Edition ⚡
      run: |
        cd "CONTINUITY LEGACY Lite"
        python -m build

    - name: Publish to PyPI 📤
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        twine upload "CONTINUITY LEGACY Pro/dist/*"
        twine upload "CONTINUITY LEGACY Lite/dist/*"
