from __future__ import annotations
import os
import sys
from pathlib import Path

PRE_COMMIT_CONTENT = """#!/bin/sh
# CHRONOLITH PRE-COMMIT HOOK
# Automatically generated by the Continental Legacy framework.

echo "[*] CHRONOLITH: Validating project state..."

# Execute the Chronolith cycle in soft mode for local commit. 
python tools/chronolith/run_chronolith_cycle.py --repo-root .

# $? captures the exit code
RESULT=$?

if [ $RESULT -ne 0 ]; then
  echo "[!] CHRONOLITH WARNING: Project state has drift."
  python tools/chronolith/chronolith_status.py --repo-root .
  echo "[!] Recommendation: Align your state before pushing to remote."
fi

exit 0
"""

PRE_PUSH_CONTENT = """#!/bin/sh
# CHRONOLITH PRE-PUSH HOOK
# Automatically generated by the Continental Legacy framework.

echo "[*] CHRONOLITH: Mandatory border control validate before push..."

# Execute the Chronolith cycle in STRICT mode for remote push.
python tools/chronolith/run_chronolith_cycle.py --repo-root . --strict

# $? captures the exit code
RESULT=$?

if [ $RESULT -ne 0 ]; then
  echo "[!] CHRONOLITH ERROR: Project state is inconsistent. Push blocked."
  python tools/chronolith/chronolith_status.py --repo-root .
  echo "[!] Please run 'python tools/chronolith/run_chronolith_cycle.py' and fix issues before pushing."
  exit 1
fi

echo "[✔] CHRONOLITH OK: Project state is valid. Proceeding with push."
exit 0
"""

def _install_hook(repo_root: str | Path, hook_name: str, content: str) -> bool:
    repo_root = Path(repo_root).resolve()
    git_dir = repo_root / ".git"
    
    if not git_dir.exists():
        return False
        
    hooks_dir = git_dir / "hooks"
    hooks_dir.mkdir(parents=True, exist_ok=True)
    
    hook_file = hooks_dir / hook_name
    
    try:
        hook_file.write_text(content, encoding="utf-8")
        if os.name != 'nt':
            os.chmod(hook_file, 0o755)
        return True
    except Exception as e:
        print(f"Error installing git hook '{hook_name}': {e}")
        return False

def install_pre_commit_hook(repo_root: str | Path) -> bool:
    return _install_hook(repo_root, "pre-commit", PRE_COMMIT_CONTENT)

def install_pre_push_hook(repo_root: str | Path) -> bool:
    return _install_hook(repo_root, "pre-push", PRE_PUSH_CONTENT)

if __name__ == "__main__":
    # Test installation in current dir
    if install_pre_commit_hook(".") and install_pre_push_hook("."):
        print("Git hooks installed successfully.")
    else:
        print("Failed to install git hooks (Are you in a git repo?).")

if __name__ == "__main__":
    # Test installation in current dir
    if install_pre_commit_hook("."):
        print("Pre-commit hook installed successfully.")
    else:
        print("Failed to install pre-commit hook (Are you in a git repo?).")
